[package]
name = "rutenspitz_macro"
description = "–ê procedural macro to be used for testing/fuzzing stateful models against a semantically equivalent but obviously correct implementation"
version = "0.2.1"
authors = ["Jakub Wieczorek <jakub.adam.wieczorek@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["fuzzing", "test", "honggfuzz"]
repository = "https://github.com/jakubadamw/rutenspitz"

[lib]
proc-macro = true

[dependencies]
either = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
